### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by Spr-Peach** [hmrishavbandy/FlipSketch#2]
I's change some requirements and the env was successfully installed.
[flipsketch.zip](https://github.com/user-attachments/files/17891558/flipsketch.zip)

then I got the error:
```powershell
(flipsketch) namiachy@namiachy-win11:~/FlipSketch$ python3 app.py
Traceback (most recent call last):
  File "/home/namiachy/miniconda3/envs/flipsketch/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 406, in hf_raise_for_status
    response.raise_for_status()
  File "/home/namiachy/.local/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/checkpoint-2500/resolve/main/scheduler/scheduler_config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/namiachy/miniconda3/envs/flipsketch/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 380, in load_config
    config_file = hf_hub_download(
  File "/home/namiachy/miniconda3/envs/flipsketch/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/home/namiachy/miniconda3/envs/flipsketch/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/namiachy/miniconda3/envs/flipsketch/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1232, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/home/namiachy/miniconda3/envs/flipsketch/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1339, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/home/namiachy/miniconda3/envs/flipsketch/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1854, in _raise_on_head_call_error
    raise head_call_error
  File "/home/namiachy/miniconda3/envs/flipsketch/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1746, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "/home/namiachy/miniconda3/envs/flipsketch/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/namiachy/miniconda3/envs/flipsketch/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1666, in get_hf_file_metadata
    r = _request_wrapper(
  File "/home/namiachy/miniconda3/envs/flipsketch/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 364, in _request_wrapper
    response = _request_wrapper(
  File "/home/namiachy/miniconda3/envs/flipsketch/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 388, in _request_wrapper
    hf_raise_for_status(response)
  File "/home/namiachy/miniconda3/envs/flipsketch/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 454, in hf_raise_for_status
    raise _format(RepositoryNotFoundError, message, response) from e
huggingface_hub.errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-6742927d-1ea742a1792452387182803a;b5e588fa-5369-48db-b86e-af4f696315c1)

Repository Not Found for url: https://huggingface.co/checkpoint-2500/resolve/main/scheduler/scheduler_config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/namiachy/FlipSketch/app.py", line 120, in <module>
    pipe_inversion, inv = initialize_pipeline(LORA_CHECKPOINT, device)
  File "/home/namiachy/FlipSketch/app.py", line 108, in initialize_pipeline
    scheduler, tokenizer, text_encoder, vae, unet = load_primary_models(model)
  File "/home/namiachy/FlipSketch/app.py", line 97, in load_primary_models
    DDPMScheduler.from_config(pretrained_model_path, subfolder="scheduler"),
  File "/home/namiachy/miniconda3/envs/flipsketch/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 245, in from_config
    config, kwargs = cls.load_config(pretrained_model_name_or_path=config, return_unused_kwargs=True, **kwargs)
  File "/home/namiachy/miniconda3/envs/flipsketch/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/namiachy/miniconda3/envs/flipsketch/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 394, in load_config
    raise EnvironmentError(
OSError: checkpoint-2500 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `token` or log in with `huggingface-cli login`.
(flipsketch) namiachy@namiachy-win11:~/FlipSketch$
``` 
please help me and thanks alot

**Comment by hmrishavbandy** [comment]
Please clone [this repository](https://huggingface.co/Hmrishav/t2v_sketch-lora) and place its contents under `checkpoint-2500`. Make sure you have git lfs installed.

**Comment by Spr-Peach** [comment]
> Please clone [this repository](https://huggingface.co/Hmrishav/t2v_sketch-lora) and place its contents under `checkpoint-2500`. Make sure you have git lfs installed.
thanks alot   it's running now after
```python
mv t2v_sketch-lora/checkpoint-2500 ./checkpoint-2500/
``` 
great works~haha
![屏幕截图 2024-11-24 202142](https://github.com/user-attachments/assets/601f7b7f-846d-46a9-917a-a31f6e822da7)

**Comment by Spr-Peach** [comment]
Why the gifs generated with user uploaded picture cannot show on the webpage please?

**Comment by hmrishavbandy** [comment]
Hi, the model runs into issues with highly complex sketches or very abstract doodles. It may be the case that none of the generated samples were good enough for the model to show. You can try increasing the number of seeds.

**Comment by Spr-Peach** [comment]
Sorry I didn't describe clearly... I mean....those gifs are actually generated, I can find them in the static folder, but they are not displayed in the preview area of ​​the web page like in the sketch tab...:)

**Comment by Spr-Peach** [comment]
> Sorry I didn't describe clearly... I mean....those gifs are actually generated, I can find them in the static folder, but they are not displayed in the preview area of ​​the web page like in the sketch tab...:)

as I git pull your gradio folder's update, it's running well now~ thanks bro~
